### ISSUE TITLE
long/lat values differ in accuracy 

### ISSUE THREAD

**Issue by aidenkeating** [NAPS-emergency-response-project/mission-service#4]
In a Mission, it's steps are accurate to 6 decimal places e.g. `-77.948448/34.170731` whereas the `responderStartLat` (and the responders themselves) are accurate to 5 decimal places e.g. `-77.94845/34.17073`.

This causes issues when trying to determine whether a responder is actually at a specific step.

**Comment by aidenkeating** [comment]
@sshaaf

**Comment by sshaaf** [comment]
currently this is purely at the mercy of JsonProperty, will need to fix both sim and mission service +  the incoming message lat/longs for mission service.
